---
title: "R Notebook"
output: pdf_document
---

#### Setup
```{r}
source("R/utils.R")
source("R/plot_utils.R")

agg_names = c(
  here("data", "processed", "BTY-1_agg.rds"),
  here("data", "processed", "FY6-1_agg.rds"),
  here("data", "processed", "JFH-1_agg.rds")
)

names = c(
  here("data", "processed", "BTY-1.rds"),
  here("data", "processed", "FY6-1.rds"),
  here("data", "processed", "JFH-1.rds")
)

raw_names = c(
  here("data", "raw", "ST003061", "BTY-1.mzML"),
  here("data", "raw", "ST003061", "FY6-1.mzML"),
  here("data", "raw", "ST003061", "JFH-1.mzML")
)

compiled_model = stan_model(file = here("models", "peak_model.stan"))
```

#### Data
```{r}
readRDS(agg_names[1])
readRDS(agg_names[2])
readRDS(agg_names[3])
```

#### Correlations
```{r}
data = readRDS(agg_names[1])

print(paste("R2 vs Position:", cor(data$mz_r2, data$mz_position)))
print(paste("Evidence vs Position:", cor(data$avg_evidence, data$mz_position)))
```

#### Plots
```{r}
plotGraph()
```

```{r}
for (i in 1:3) {
  
  plotMSAgg(agg_names[i])
  plotEvidence(names[i])
  plotPrec(names[i])
  plotAmp(names[i])
}
```

```{r}
plotPPC(here("data", "processed", "BTY-2.rds"), here("data", "raw", "ST003061", "BTY-2.mzML"))
```

```{r}
plotPairs(here("data", "processed", "BTY-2.rds"), here("data", "raw", "ST003061", "BTY-2.mzML"), compiled_model)
```

